# Generated by Django 3.2.6 on 2023-03-02 23:32

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Etablissement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('raisonSociale', models.CharField(max_length=255, unique=True, verbose_name='raison sociale')),
                ('sigle', models.CharField(blank=True, default='', max_length=50, null=True, verbose_name='sigle')),
                ('telephone', models.CharField(blank=True, default='', max_length=20, null=True, verbose_name='téléphone')),
                ('cellulaire', models.CharField(blank=True, default='', max_length=20, null=True, verbose_name='cellulaire')),
                ('email', models.EmailField(blank=True, default='', max_length=254, null=True, verbose_name='e-mail')),
                ('dateCreation', models.DateField(blank=True, default=django.utils.timezone.now, null=True, verbose_name='date envoi des email')),
                ('historique', models.TextField(blank=True, default='', null=True, verbose_name='historique')),
                ('logo', models.ImageField(blank=True, default='', null=True, upload_to='images', verbose_name='logo')),
                ('photo', models.ImageField(blank=True, default='', null=True, upload_to='images', verbose_name='photo')),
            ],
        ),
    ]
