# Generated by Django 3.2.6 on 2023-03-03 01:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('parametre', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Fonction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('libelle', models.CharField(max_length=50, unique=True, verbose_name='Libellé')),
            ],
            options={
                'ordering': ('libelle',),
            },
        ),
        migrations.CreateModel(
            name='Profession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('libelle', models.CharField(max_length=50, unique=True, verbose_name='Libellé')),
            ],
            options={
                'ordering': ('libelle',),
            },
        ),
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('matricule', models.CharField(max_length=15, unique=True, verbose_name='matricule')),
                ('civilite', models.CharField(blank=True, choices=[('Monsieur', 'M.'), ('Madame', 'Mme'), ('Mademoiselle', 'Mlle')], max_length=20, verbose_name='civilité')),
                ('nom', models.CharField(max_length=50, verbose_name='nom')),
                ('prenoms', models.CharField(max_length=100, verbose_name='prenoms')),
                ('telephone', models.CharField(blank=True, default='', max_length=20, null=True, verbose_name='téléphone')),
                ('cellulaire', models.CharField(blank=True, default='', max_length=20, null=True, verbose_name='cellulaire')),
                ('email', models.CharField(blank=True, default='', max_length=100, null=True, verbose_name='e-mail')),
                ('sexe', models.CharField(choices=[('M', 'Masculin'), ('F', 'Féminin')], default='M', max_length=1, verbose_name='sexe')),
                ('photo', models.ImageField(blank=True, null=True, upload_to='users', verbose_name='photo')),
                ('fonction', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='parametre.fonction', verbose_name='fonction')),
                ('profession', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='parametre.profession', verbose_name='profession')),
            ],
        ),
        migrations.CreateModel(
            name='Medecin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('matricule', models.CharField(max_length=15, unique=True, verbose_name='matricule')),
                ('civilite', models.CharField(blank=True, choices=[('Monsieur', 'M.'), ('Madame', 'Mme'), ('Mademoiselle', 'Mlle')], max_length=20, verbose_name='civilité')),
                ('nom', models.CharField(max_length=50, verbose_name='nom')),
                ('prenoms', models.CharField(max_length=100, verbose_name='prenoms')),
                ('telephone', models.CharField(blank=True, default='', max_length=20, null=True, verbose_name='téléphone')),
                ('cellulaire', models.CharField(blank=True, default='', max_length=20, null=True, verbose_name='cellulaire')),
                ('email', models.CharField(blank=True, default='', max_length=100, null=True, verbose_name='e-mail')),
                ('sexe', models.CharField(choices=[('M', 'Masculin'), ('F', 'Féminin')], default='M', max_length=1, verbose_name='sexe')),
                ('photo', models.ImageField(blank=True, null=True, upload_to='users', verbose_name='photo')),
                ('fonction', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='parametre.fonction', verbose_name='fonction')),
                ('profession', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='parametre.profession', verbose_name='profession')),
            ],
        ),
    ]
