# Generated by Django 4.1 on 2023-03-12 11:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('connexion', '0003_alter_user_email_alter_user_username'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='username',
        ),
    ]
