# Generated by Django 4.1 on 2023-03-14 01:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('connexion', '0006_alter_user_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(max_length=255, unique=True),
        ),
    ]
